services:
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongo:27017/tododb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    restart: always
    networks:
      - backend

  mongo:
    image: mongo
    ports:
      - '3456:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - backend

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
    driver: bridge
