services:
  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/tododb
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./todo-backend:/usr/src/app
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    volumes:
      - ./todo-frontend:/usr/src/app
    depends_on:
      - nginx
    networks:
      - app-network

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - todo-frontend
      - todo-backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: tododb
    volumes:
      - ./mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
